import { BreakdownItem, TrendPoint, formatMinutesOfDay } from '@/lib/stats';

function LineChart({ title, points, field, format }: { title:string; points:TrendPoint[]; field:'arrivalMinutes'|'durationMinutes'; format:(v:number)=>string }) {
  const values=points.map(p=>p[field]).filter((v):v is number=>v!==null);
  if(values.length<2)return <div className="rounded-xl border border-dashed border-slate-200 p-5 text-sm text-slate-500"><strong className="block text-slate-700">{title}</strong><span className="mt-2 block">차트를 그리려면 유효한 기록이 2건 이상 필요해요.</span></div>;
  const min=Math.min(...values),max=Math.max(...values),span=Math.max(1,max-min); let index=0;
  const coords=points.flatMap((point,i)=>{const value=point[field];if(value===null)return[];const x=points.length===1?50:i/(points.length-1)*100,y=88-(value-min)/span*70;return[{x,y,value,label:point.label,key:index++}];});
  return <figure className="rounded-xl border border-slate-200 p-4"><figcaption className="text-sm font-bold text-slate-800">{title}</figcaption><svg viewBox="0 0 100 100" className="mt-3 h-44 w-full overflow-visible" role="img" aria-label={`${title} 선 그래프`}><line x1="0" y1="88" x2="100" y2="88" stroke="#e2e8f0"/><polyline points={coords.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#2563eb" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{coords.map(p=><g key={p.key}><circle cx={p.x} cy={p.y} r="2.2" fill="#2563eb"><title>{p.label} {format(p.value)}</title></circle><text x={p.x} y="98" textAnchor="middle" fontSize="4" fill="#64748b">{p.label}</text></g>)}</svg><div className="mt-1 flex justify-between text-xs text-slate-400"><span>{format(min)}</span><span>최고 {format(max)}</span></div></figure>;
}
function Breakdown({title,items,kind}:{title:string;items:BreakdownItem[]|null;kind:'weather'|'transport'}){if(!items)return <div className="rounded-xl border border-dashed border-slate-200 p-5 text-sm text-slate-500"><strong className="block text-slate-700">{title}</strong><span className="mt-2 block">{kind==='weather'?'날씨 필드가 있는 이동 기록이 부족해요.':'교통수단 필드가 있는 이동 기록이 부족해요.'}</span></div>;const total=items.reduce((s,i)=>s+i.count,0);return <div className="rounded-xl border border-slate-200 p-4"><h3 className="text-sm font-bold text-slate-800">{title}</h3><ul className="mt-4 space-y-3">{items.map(item=><li key={item.label}><div className="flex justify-between text-xs"><span>{item.label}</span><span>{kind==='transport'?`${Math.round(item.count/total*100)}%`:`평균 ${item.averageMinutes??'-'}분`}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{width:`${item.count/total*100}%`}}/></div></li>)}</ul></div>}
export default function StatsCharts({points,weather,transport}:{points:TrendPoint[];weather:BreakdownItem[]|null;transport:BreakdownItem[]|null}){return <div className="grid gap-4 md:grid-cols-2"><LineChart title="출근 도착 시각 추이" points={points} field="arrivalMinutes" format={formatMinutesOfDay}/><LineChart title="이동시간 추이" points={points} field="durationMinutes" format={v=>`${v}분`}/><Breakdown title="날씨별 이동시간" items={weather} kind="weather"/><Breakdown title="교통수단 비율" items={transport} kind="transport"/></div>}
