package com.example.gestureOSManager.dto;

public enum CommandType {
	ENABLE, DISABLE, SET_MODE, UPDATE_SETTINGS, PING, SET_PREVIEW, SET_LOCK, SET_GAIN,
	// 트레이닝용 추가
	TRAIN_CAPTURE, TRAIN_TRAIN, TRAIN_ENABLE, TRAIN_RESET,
	 // profiles
	TRAIN_SET_PROFILE, TRAIN_PROFILE_CREATE, TRAIN_PROFILE_DELETE, TRAIN_PROFILE_RENAME
	, TRAIN_ROLLBACK
}	
