// src/config/templateSummaryConfig.js
export const TEMPLATE_MAIN_PLACEHOLDER = {
  TPL1: [
    '예시)',
    '월요일: 분석모델 검증 및 문서 작성',
    '화요일: 회의 참석 및 이슈 정리',
    '수요일: 테스트 진행 및 결과 정리',
    '목요일: 개선 사항 반영',
    '금요일: 주간 업무 정리',
    '',
    '특이사항/건의사항도 함께 적어 주세요.',
  ].join('\n'),

  TPL3: [
    '예시)',
    '작성일: 2025-12-06',
    '작성자: 홍길동',
    '',
    '금일 업무 내용:',
    '- 분석모델 검증 및 시스템화 타당성 분석을 수행하였습니다.',
    '',
    '비고:',
    '- 특이사항 없음',
  ].join('\n'),

  TPL4: [
    '예시)',
    '보고서 번호/제목: 2025-12-1차 주간보고',
    '작성일: 2025-12-06',
    '부서명: 분석팀',
    '작성자: 홍길동',
    '',
    '오늘 업무 내용:',
    '- 모델 검증 결과 공유 및 개선 방향 논의',
    '',
    '다음 작업/계획:',
    '- 개선 모델 설계 및 시뮬레이션 예정',
  ].join('\n'),

  TPL5: [
    '예시)',
    '작성일: 2025-12-06',
    '프로젝트/업무 구분: 사내 인트라넷 개선',
    '업무 ID/번호: T-001',
    '업무 분류: 개발',
    '',
    '업무 상세 내용:',
    '- 로그인 기능 개선 및 오류 수정',
    '',
    '담당자: 홍길동',
    '진행 상태: 진행중',
  ].join('\n'),

  TPL6: [
    '예시)',
    '작성일: 2025-12-06',
    '팀/부서명: 백엔드팀',
    '작성자: 홍길동',
    '',
    '오늘 업무 요약:',
    '- API 성능 개선 작업 진행',
    '',
    '오늘 발생 이슈:',
    '- 특정 요청에서 응답 지연 발생',
    '',
    '내일/다음 계획:',
    '- 원인 분석 후 캐싱 적용 예정',
  ].join('\n'),

  TPL7: [
    '예시)',
    '프로젝트/공사명: 분석모델 검증 및 시스템화 타당성 분석',
    '오늘 작업 제목: 요구사항 확인 프로세스',
    '',
    '오늘 작업 상세:',
    '- 요구사항을 바탕으로 분석모델의 적합성 검토',
    '',
    '현장 특이사항:',
    '- 이해관계자와 추가 협의 필요',
    '',
    '투입 인원 수: 3명',
    '사용 장비: 특별한 장비는 사용하지 않음',
    '사용 자재/소모품: 문서 및 소프트웨어 도구 사용',
    '',
    '다음 작업 계획:',
    '- 의견 정리 후 추적표에 기록 예정',
  ].join('\n'),
};
// ✅ 템플릿별 필드 출력 순서
export const FIELD_ORDER = {
  TPL1: [
    'TPL1_DATE',
    'TPL1_MON_TASK_TODAY',
    'TPL1_MON_TASK_NEXT',
    'TPL1_TUE_TASK_TODAY',
    'TPL1_TUE_TASK_NEXT',
    'TPL1_WED_TASK_TODAY',
    'TPL1_WED_TASK_NEXT',
    'TPL1_THU_TASK_TODAY',
    'TPL1_THU_TASK_NEXT',
    'TPL1_FRI_TASK_TODAY',
    'TPL1_FRI_TASK_NEXT',
    'TPL1_SAT_TASK_TODAY',
    'TPL1_SAT_TASK_NEXT',
    'TPL1_SUGGESTIONS',
  ],
  TPL3: [
    'TPL3_DATE',
    'TPL3_AUTHOR',
    'TPL3_CONTENT',
    'TPL3_NOTE',
    'TPL3_SUMMARY',
  ],
  TPL4: [
    'TPL4_REPORT_ID',
    'TPL4_DATE',
    'TPL4_DEPT',
    'TPL4_AUTHOR',
    'TPL4_TODAY_TASKS',
    'TPL4_NEXT_PLAN',
    'TPL4_NOTE',
  ],
  TPL5: [
    'TPL5_DATE',
    'TPL5_PROJECT',
    'TPL5_TASK_ID',
    'TPL5_CATEGORY',
    'TPL5_DETAIL',
    'TPL5_MANAGER',
    'TPL5_STATUS',
  ],
  TPL6: [
    'TPL6_DATE',
    'TPL6_TEAM',
    'TPL6_AUTHOR',
    'TPL6_TODAY_TASKS',
    'TPL6_TODAY_ISSUE',
    'TPL6_NEXT_PLAN',
    'TPL6_DETAILS',
    'TPL6_ETC',
  ],
  TPL7: [
    'TPL7_PROJECT_NAME',
    'TPL7_TASK_NOTE',
    'TPL7_TODAY_WORK_DETAIL',
    'TPL7_OTHER_NOTES',
    'TPL7_PERSONNEL_COUNT',
    'TPL7_EQUIPMENT_DETAIL',
    'TPL7_MATERIAL_DETAIL',
    'TPL7_NEXT_PLAN_DETAIL',
    'TPL7_NEXT_PERSONNEL_PLAN',
    'TPL7_NEXT_EQUIPMENT_PLAN',
    'TPL7_NEXT_MATERIAL_PLAN',
    'TPL7_NEXT_OTHER_NOTES',
    // ⛔ 여기에는 TPL1_DATE 안 넣음
  ],
};

// ✅ 템플릿별 필드 한글 라벨
export const FIELD_LABELS = {
  TPL1: {
    TPL1_DATE: '작성일(주간 시작일)',
    TPL1_MON_TASK_TODAY: '월요일 - 오늘 한 일',
    TPL1_MON_TASK_NEXT: '월요일 - 내일/다음 할 일',
    TPL1_TUE_TASK_TODAY: '화요일 - 오늘 한 일',
    TPL1_TUE_TASK_NEXT: '화요일 - 내일/다음 할 일',
    TPL1_WED_TASK_TODAY: '수요일 - 오늘 한 일',
    TPL1_WED_TASK_NEXT: '수요일 - 내일/다음 할 일',
    TPL1_THU_TASK_TODAY: '목요일 - 오늘 한 일',
    TPL1_THU_TASK_NEXT: '목요일 - 내일/다음 할 일',
    TPL1_FRI_TASK_TODAY: '금요일 - 오늘 한 일',
    TPL1_FRI_TASK_NEXT: '금요일 - 내일/다음 할 일',
    TPL1_SAT_TASK_TODAY: '토요일 - 오늘 한 일',
    TPL1_SAT_TASK_NEXT: '토요일 - 내일/다음 할 일',
    TPL1_SUGGESTIONS: '특이사항 / 건의사항',
  },
  TPL3: {
    TPL3_DATE: '작성일',
    TPL3_AUTHOR: '작성자',
    TPL3_CONTENT: '금일 업무 내용',
    TPL3_NOTE: '비고',
    TPL3_SUMMARY: '금일 업무 요약',
  },
  TPL4: {
    TPL4_REPORT_ID: '보고서 번호 / 제목',
    TPL4_DATE: '작성일',
    TPL4_DEPT: '부서명',
    TPL4_AUTHOR: '작성자',
    TPL4_TODAY_TASKS: '오늘 업무 내용',
    TPL4_NEXT_PLAN: '다음 작업 / 계획',
    TPL4_NOTE: '비고',
  },
  TPL5: {
    TPL5_DATE: '작성일',
    TPL5_PROJECT: '프로젝트 / 업무 구분',
    TPL5_TASK_ID: '업무 ID / 번호',
    TPL5_CATEGORY: '업무 분류',
    TPL5_DETAIL: '업무 상세 내용',
    TPL5_MANAGER: '담당자',
    TPL5_STATUS: '진행 상태',
  },
  TPL6: {
    TPL6_DATE: '작성일',
    TPL6_TEAM: '팀 / 부서명',
    TPL6_AUTHOR: '작성자',
    TPL6_TODAY_TASKS: '오늘 업무 요약',
    TPL6_TODAY_ISSUE: '오늘 발생 이슈',
    TPL6_NEXT_PLAN: '내일 / 다음 계획',
    TPL6_DETAILS: '세부 내용',
    TPL6_ETC: '기타 특이사항',
  },
  TPL7: {
    TPL7_PROJECT_NAME: '프로젝트 / 공사명',
    TPL7_TASK_NOTE: '오늘 작업 제목',
    TPL7_TODAY_WORK_DETAIL: '오늘 작업 상세',
    TPL7_OTHER_NOTES: '현장 특이사항',
    TPL7_PERSONNEL_COUNT: '투입 인원 수',
    TPL7_EQUIPMENT_DETAIL: '사용 장비',
    TPL7_MATERIAL_DETAIL: '사용 자재 / 소모품',
    TPL7_NEXT_PLAN_DETAIL: '다음 작업 계획',
    TPL7_NEXT_PERSONNEL_PLAN: '다음 작업 인력 계획',
    TPL7_NEXT_EQUIPMENT_PLAN: '다음 작업 장비 계획',
    TPL7_NEXT_MATERIAL_PLAN: '다음 작업 자재 계획',
    TPL7_NEXT_OTHER_NOTES: '다음 작업 관련 메모',
  },
};
